#!/usr/bin/env python3

import script_2
import os


def create():
    documents = os.popen(
        "git diff --cached --name-status").read().splitlines()  # Pega todos os documentos dentro da cache prestes a serem comitados
    i = 0
    alcance = len(documents)
    while i < alcance:
        full_line = documents[i].split()
        if full_line[0] == "R100":
            documents[i] = full_line[2]
            i += 1
        elif full_line[0] == "D":
            documents.pop(i)
            alcance -= 1
        else:
            documents[i] = full_line[1]
            i += 1
    block = 0
    resp = "Testes OK. Commit Realizado"
    i = 0

    for i in range(len(documents)):
        r = script_2.main(documents[i])  # Faz a verificacao definida em scriptPat.Compare
        if r == 0:
            print(documents[i] + " : Teste realizado com sucesso")
        else:
            resp = "Nao commitado"
            block = 1
    print(resp)
    os._exit(block)  # Bloqueia o commit


if __name__ == '__main__':
    create()