#!/usr/bin/env python3

# chmod +x ~/Documents/git_python_script/src/git_script.py
# echo "Printing the folders that was changed by the last commit\n"
# cd ~/Documents/git_python_script/src/git_script.py
# ./git_script.py
# echo "\n"

# Read the README.md file for more details on how the script is working...
import os


def create():
    """Get the hash of the last commited commit"""
    #message = os.popen("git log -n 1 master --pretty=format:\"%H\"").read()    
    message = os.popen("git diff --cached --name-status | cut -f2").read()


    full_path = os.popen("readlink -f {}").format(message)read()	

    sys_message = os.system(message)
    sys_full_path = os.system(full_path)
    return sys_full_path


if __name__ == '__main__':
    create()

