#!/usr/bin/env python3

# chmod +x ~/Documents/git_python_script/src/git_script.py
# echo "Printing the folders that was changed by the last commit\n"
# cd ~/Documents/git_python_script/src/git_script.py
# ./git_script.py
# echo "\n"

# Read the README.md file for more details on how the script is working...
import os
from script_2 import *


def create():
    # message = os.popen("git diff --cached --name-status | cut -f2").read().splitlines()
    var = ["Orch_Consult_Customer/resource/transformation/DTIN_CC_Blabla.xsl",
           "Orch_Consult_Service/resource/transformation/DTIN_CC_DleDleDle.xsl",
           "Orch_Consult_Owner/resource/transformation/DTIN_CC_ClaClaCla.xsl"]
    for i in range(len(var)):
        aux = main(var[i])
        if aux == 0:
            print(aux)
        else:
            print("You have a problem with your commit, please check it")
            os._exit(1)


if __name__ == '__main__':
    create()
